[package]
name = "luddScreen"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = {version = "0.17.2"}
image = {version = "0.23.14"}
